---
language: python
python: "2.7"
sudo: required

services:
  - mysql

env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  # Install Ansible.
  - pip install ansible==2.0.2

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  - ansible-galaxy install geerlingguy.apache,1.4.2 -p `pwd`/..

before_script:
  - mysql -u root -e 'create database storyboard;'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON storyboard.* TO storyboard@localhost IDENTIFIED BY 'storyboard'"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "travis_wait ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"
