# Instance-specific configuration for the baserock.org StoryBoard system.
- hosts: storyboard
  vars_files:
  - vars.yml
  sudo: yes
  roles:
  - { role: Mayeu.RabbitMQ }
  - { role: geerlingguy.mysql, when: mysql_host == 'localhost' }
  - { role: palvarez89.storyboard }
