# Instance-specific configuration for the baserock.org StoryBoard system.
- hosts: storyboard
  vars_files:
  - vars.yml
  sudo: yes
  roles:
  - { role: geerlingguy.apache }
  - { role: Mayeu.RabbitMQ }
  - { role: geerlingguy.mysql, when: mysql_host == 'localhost' }

  tasks:

  - name: Install packages needed from apt
    apt:
      pkg: "{{ item }}"
      state: present
      update-cache: yes
    with_items:
    - libapache2-mod-wsgi
    - curl
    - git
    - python-pip
    - python-dev

  - name: Install apache modules needed
    apache2_module:
      name: "{{ item }}"
      state: present
    with_items:
    - wsgi


  - name: create /etc/storyboard
    file:
      path: /etc/storyboard
      state: directory

  - name: install storyboard.conf
    template:
      src: templates/storyboard.conf.j2
      dest: /etc/storyboard/storyboard.conf

  - git:
      repo: https://github.com/openstack-infra/storyboard
      dest: "{{ src_root_api }}"
      update: yes

  - name: Setup virtual environment for the app using requirements.txt
    pip:
      requirements: "{{ src_root_api }}/requirements.txt"

  - shell: python {{ src_root_api }}/setup.py install
    args:
      chdir: "{{ src_root_api }}"

  - name: Create more folders needed for storyboard and apache2
    file:
      path: "{{ item }}"
      state: directory
      owner: www-data
      group: www-data
    with_items:
    - "{{ install_root }}"
    - "{{ working_root }}"
    - "{{ www_root }}"
    - /var/log/storyboard

  - name: Install wsgi of StoryBoard
    command: install -g www-data -o www-data {{ src_root_api }}/storyboard/api/app.wsgi {{ install_root }}/storyboard.wsgi

  - name: DEPS NEEDED?
    pip:
      name: "{{ item }}"
    with_items:
    - oslo.serialization
    - debtcollector
    - webob
    - singledispatch

  - name: Migrate the database
    command: storyboard-db-manage --config-file /etc/storyboard/storyboard.conf upgrade head

  - name: Create more folders needed for storyboard-webclient
    file:
      path: "{{ item }}"
      state: directory
      owner: www-data
      group: www-data
    with_items:
    - "{{ src_root_webclient }}"

  - name: Download StoryBoard webclient
    get_url:
      url: "{{ webclient_url }}"
      dest: "{{ src_root_webclient }}/{{ webclient_filename }}"
      force: yes
    register: new_webclient

  - name: Unpack storyboard-webclient
    unarchive:
      src: "{{ src_root_webclient }}/{{ webclient_filename }}"
      dest: "{{ src_root_webclient }}"
      copy: no
      owner: www-data
      group: www-data
    when: new_webclient|changed

  - name: Create config.json
    shell: echo "{}" > {{ src_root_webclient }}/dist/config.json
    args:
      creates: "{{ src_root_webclient }}/dist/config.json"

  - name: Copy storyboard-webclient into the configured www_root
    shell: cp -r "{{ src_root_webclient }}"/dist/* "{{ www_root }}"


  - name: install Virtualhost for storyboard
    template:
      src: templates/vhost-storyboard.conf
      dest: /etc/apache2/sites-available/vhost-storyboard.conf

  - name: enable storyboard Virtualhost
    file:
      src: ../sites-available/vhost-storyboard.conf
      dest: /etc/apache2/sites-enabled/vhost-storyboard.conf
      state: link
