---
# tasks file for ansible-role-storyboard
- name: Install packages needed from apt
  apt:
    pkg: "{{ item }}"
    state: present
    update-cache: yes
  with_items:
  - libapache2-mod-wsgi
  - curl
  - git
  - python-pip
  - python-dev
  - libmysqlclient-dev

- name: Install apache modules needed
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
  - wsgi

- name: create /etc/storyboard
  file:
    path: /etc/storyboard
    state: directory

- name: install storyboard.conf
  template:
    src: storyboard.conf.j2
    dest: /etc/storyboard/storyboard.conf

- git:
    repo: https://github.com/openstack-infra/storyboard
    dest: "{{ storyboard_src_root_api }}"
    update: yes
  notify: restart apache

- name: Setup virtual environment for the app using requirements.txt
  pip:
    requirements: "{{ storyboard_src_root_api }}/requirements.txt"

- shell: python {{ storyboard_src_root_api }}/setup.py install
  args:
    chdir: "{{ storyboard_src_root_api }}"

- name: Create more folders needed for storyboard and apache2
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
  with_items:
  - "{{ storyboard_install_root }}"
  - "{{ storyboard_working_root }}"
  - "{{ storyboard_www_root }}"
  - /var/log/storyboard

- name: Install wsgi of StoryBoard
  command: install -g www-data -o www-data {{ storyboard_src_root_api }}/storyboard/api/app.wsgi {{ storyboard_install_root }}/storyboard.wsgi
  notify: restart apache

- name: DEPS NEEDED?
  pip:
    name: "{{ item }}"
  with_items:
  - oslo.serialization
  - debtcollector
  - webob
  - singledispatch

- name: Migrate the database
  command: storyboard-db-manage --config-file /etc/storyboard/storyboard.conf upgrade head

- name: Install tox
  pip:
    name: tox

- name: Create more folders needed for storyboard-webclient
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
  with_items:
  - "{{ storyboard_src_root_webclient }}"

- git:
    repo: https://github.com/openstack-infra/storyboard-webclient
    dest: "{{ storyboard_src_root_webclient }}"
    update: yes
    force: yes
  sudo_user: www-data

- lineinfile:
    dest: "{{ storyboard_src_root_webclient }}/src/theme/storyboard/theme.less"
    regexp: "^@brand-primary:"
    line: "@brand-primary: #006566;"
    backrefs: yes
  sudo_user: www-data

- command: tox -egrunt build
  args:
    chdir: "{{ storyboard_src_root_webclient}}"
  sudo_user: www-data

- name: Create config.json
  shell: echo "{}" > {{ storyboard_src_root_webclient }}/dist/config.json
  args:
    creates: "{{ storyboard_src_root_webclient }}/dist/config.json"
  sudo_user: www-data

- name: Copy storyboard-webclient into the configured www_root
  shell: cp -r "{{ storyboard_src_root_webclient }}"/dist/* "{{ storyboard_www_root }}"

- copy:
    src: "{{ storyboard_ssl_cert }}"
    dest: "/etc/ssl/certs/{{ storyboard_ssl_cert | basename }}"
  when: storyboard_ssl_cert is defined

- copy:
    src: "{{ storyboard_ssl_key }}"
    dest: "/etc/ssl/private/{{ storyboard_ssl_key | basename }}"
  when: storyboard_ssl_key is defined

- copy:
    src: "{{ storyboard_resolved_ssl_ca }}"
    dest: "/etc/ssl/certs/{{ storyboard_resolved_ssl_ca | basename }}"
  when: storyboard_resolved_ssl_ca is defined

- set_fact:
    storyboard_vhost_protocol: http
  when: storyboard_ssl_cert is not defined or storyboard_ssl_key is not defined

- set_fact:
    storyboard_vhost_protocol: https
  when: storyboard_ssl_cert is defined and storyboard_ssl_key is defined

- name: install Virtualhost for storyboard
  template:
    src: storyboard_{{ storyboard_vhost_protocol }}.vhost.j2
    dest: /etc/apache2/sites-available/vhost-storyboard.conf
  notify: restart apache

- name: enable storyboard Virtualhost
  file:
    src: ../sites-available/vhost-storyboard.conf
    dest: /etc/apache2/sites-enabled/vhost-storyboard.conf
    state: link
  notify: restart apache

- name: Set up Upstart configuration for StoryBoard workers
  template:
    src: storyboard-workers.conf.j2
    dest: /etc/init/storyboard-workers.conf
    mode: 0644
  when: storyboard_use_upstart

- name: Set up SysVinit configuration for StoryBoard workers
  template:
    src: storyboard-workers.sh.j2
    dest: /etc/init.d/storyboard-workers
    mode: 0755
  when: not storyboard_use_upstart

- name: Start storyboard-workers service
  service:
    name: storyboard-workers
    state: started
