---
- name: restart storyboard-workers
  service:
    name: storyboard-workers
    state: restarted

- name: restart rabbitmq-server
  service:
    name: rabbitmq-server
    state: restarted
    enabled: yes
